# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'donnesper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QWidget, QMessageBox
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets


class donnes(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(779, 849)
        self.frame_central = QtWidgets.QFrame(Form)
        self.frame_central.setGeometry(QtCore.QRect(0, 0, 781, 851))
        self.frame_central.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_central.setObjectName("frame_central")
        self.label = QtWidgets.QLabel(self.frame_central)
        self.label.setGeometry(QtCore.QRect(0, 0, 781, 861))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("2022_ani_cartoon_70.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_labels = QtWidgets.QFrame(self.frame_central)
        self.frame_labels.setGeometry(QtCore.QRect(0, 0, 111, 741))
        self.frame_labels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_labels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_labels.setObjectName("frame_labels")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_labels)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_id = QtWidgets.QLabel(self.frame_labels)
        self.label_id.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"")
        self.label_id.setObjectName("label_id")
        self.verticalLayout.addWidget(self.label_id)
        self.label_nom = QtWidgets.QLabel(self.frame_labels)
        self.label_nom.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_nom.setObjectName("label_nom")
        self.verticalLayout.addWidget(self.label_nom)
        self.label_prenom = QtWidgets.QLabel(self.frame_labels)
        self.label_prenom.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_prenom.setObjectName("label_prenom")
        self.verticalLayout.addWidget(self.label_prenom)
        self.label_tel = QtWidgets.QLabel(self.frame_labels)
        self.label_tel.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_tel.setObjectName("label_tel")
        self.verticalLayout.addWidget(self.label_tel)
        self.label_spec = QtWidgets.QLabel(self.frame_labels)
        self.label_spec.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_spec.setObjectName("label_spec")
        self.verticalLayout.addWidget(self.label_spec)
        self.label_adr = QtWidgets.QLabel(self.frame_labels)
        self.label_adr.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_adr.setObjectName("label_adr")
        self.verticalLayout.addWidget(self.label_adr)
        self.frame = QtWidgets.QFrame(self.frame_central)
        self.frame.setGeometry(QtCore.QRect(109, 9, 291, 1211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(0, 50, 151, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 160, 261, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 280, 271, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 400, 191, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 510, 291, 71))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_6.setGeometry(QtCore.QRect(0, 630, 291, 87))
        self.textEdit_6.setObjectName("textEdit_6")
        #self.butt_mod = QtWidgets.QPushButton(self.frame)
        #self.butt_mod.setGeometry(QtCore.QRect(30, 750, 101, 31))
        #self.butt_mod.setStyleSheet("background-color: rgb(170, 255, 255);")
       # self.butt_mod.setObjectName("butt_mod")
        self.butt_retour = QtWidgets.QPushButton(self.frame)
        self.butt_retour.setGeometry(QtCore.QRect(160, 750, 101, 31))
        self.butt_retour.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.butt_retour.setObjectName("butt_retour")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.db = mysql.connector.connect(
            host='localhost',
            user='root',
            password='',
            database='texthear'
       )
    
    def afficher_info(self):
        cursor = self.db.cursor()
        id = self.textEdit.toPlainText()  # Récupérer l'ID du secrétaire depuis l'interface
        query = f"SELECT nom, prénom, specialite, numero_telephone, adresse FROM medecin WHERE id = {id}"  # Créer la requête SQL pour récupérer les informations du secrétaire
        cursor.execute(query)  # Exécuter la requête SQL
        result = cursor.fetchone()  # Récupérer le résultat de la requête

        if result: # si le résultat de la requête n'est pas vide
            # afficher les informations du secrétaire sur les labels
            
            self.textEdit_2.setText(f"Nom: {result[0]}")
            self.textEdit_3.setText(f"Prénom: {result[1]}")
            self.textEdit_5.setText(f"specialite: {result[2]}")
            self.textEdit_4.setText(f"Numéro de téléphone: {result[3]}")
            self.textEdit_6.setText(f"Adresse: {result[4]}")
        else: # si le résultat de la requête est vide
            messageBox = QMessageBox()
            messageBox.setText("'Erreur Le medecin n\'a pas été trouvé dans la base de données")
            messageBox.setStandardButtons(QMessageBox.Ok)
            messageBox.exec() 

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_id.setText(_translate("Form", "ID_MED:"))
        self.label_nom.setText(_translate("Form", "NOM:"))
        self.label_prenom.setText(_translate("Form", "PRENOM:"))
        self.label_tel.setText(_translate("Form", "NUM TEL:"))
        self.label_spec.setText(_translate("Form", "SPECIALITE:"))
        self.label_adr.setText(_translate("Form", "ADRESSE:"))
       # self.butt_mod.setText(_translate("Form", "MODIFIER"))
        self.butt_retour.setText(_translate("Form", "AFFICHER"))
        self.butt_retour.clicked.connect(self.afficher_info)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form3 = QtWidgets.QWidget()
    ui3 = donnes()
    ui3.setupUi(Form3)
    Form3.show()
    sys.exit(app.exec_())
