# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LOG31.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys



import pymysql
import os




from PyQt5.QtWidgets import QApplication, QDialog, QGridLayout, QLabel, QLineEdit, QPushButton, QMessageBox

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1786, 1232)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -10, 1261, 911))
        self.label.setStyleSheet("background-image: url(:/newPrefix/doctor-with-medical-mask-background-vector.jpg);")
        self.label.setObjectName("label")
        self.nomuti = QtWidgets.QLineEdit(Form)
        self.nomuti.setGeometry(QtCore.QRect(380, 220, 321, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nomuti.sizePolicy().hasHeightForWidth())
        self.nomuti.setSizePolicy(sizePolicy)
        self.nomuti.setStyleSheet("border :none;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0,0);\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"padding-bottom:7px\n"
"")
        self.nomuti.setInputMethodHints(QtCore.Qt.ImhNone)
        self.nomuti.setInputMask("")
        self.nomuti.setText("")
        self.nomuti.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nomuti.setDragEnabled(False)
        self.nomuti.setReadOnly(False)
        self.nomuti.setObjectName("nomuti")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(500, 70, 581, 61))
        self.label_6.setStyleSheet("font: 87 28pt \"Arial Black\";\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.motdepass = QtWidgets.QLineEdit(Form)
        self.motdepass.setGeometry(QtCore.QRect(380, 330, 291, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motdepass.sizePolicy().hasHeightForWidth())
        self.motdepass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.motdepass.setFont(font)
        self.motdepass.setStyleSheet("border :none;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0,0);\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"padding-bottom:7px\n"
"")
        self.motdepass.setInputMask("")
        self.motdepass.setText("")
        self.motdepass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.motdepass.setObjectName("motdepass")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(390, 480, 281, 41))
        self.checkBox_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.connect = QtWidgets.QPushButton(Form)
        self.connect.setGeometry(QtCore.QRect(460, 670, 341, 71))
        self.connect.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 0);")
        self.connect.setObjectName("connect")
        self.compte = QtWidgets.QPushButton(Form)
        self.compte.setGeometry(QtCore.QRect(910, 670, 351, 71))
        self.compte.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 0);")
        self.compte.setObjectName("compte")
        #self.commandLinkButton = QtWidgets.QCommandLinkButton(Form)
        #self.commandLinkButton.setGeometry(QtCore.QRect(50, 910, 271, 91))
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap("kisspng-button-download-icon-previous-button-transparent-background-5a77bbc5cd5779.1893000015177962938411.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #self.commandLinkButton.setIcon(icon)
        #self.commandLinkButton.setIconSize(QtCore.QSize(60, 90))
        #self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(830, 480, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(380, 420, 411, 41))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><img src=\"doctor-with-medical-mask-background-vector.jpg\"/></p></body></html>"))
        self.nomuti.setPlaceholderText(_translate("Form", "Email"))
        self.label_6.setText(_translate("Form", "Connexion Médecin"))
        self.motdepass.setPlaceholderText(_translate("Form", "Mot de passe"))
        self.checkBox_2.setText(_translate("Form", "Garder ma session active"))
        self.connect.setText(_translate("Form", "Connecter"))
        self.compte.setText(_translate("Form", "Créer un compte"))
        #self.commandLinkButton.setText(_translate("Form", "Page Précédente"))
        self.pushButton.setWhatsThis(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/doctor-with-medical-mask-background-vector.jpg\"/></p></body></html>"))
        self.pushButton.setText(_translate("Form", " Mot de passe oublié ?"))
        self.connect.clicked.connect(self.connect_medecin)
        self.pushButton.clicked.connect(self.reset_password)



        
    def connect_medecin(self):
        email = self.nomuti.text()
        password = self.motdepass.text()

        mydb = pymysql.connect(
            host="localhost",
            user="root",
            password="",
            database="texthear"
        )

        mycursor = mydb.cursor()

        query = "SELECT * FROM medecin WHERE email = %s AND password = %s"
        values = (email, password)
        mycursor.execute(query, values)

        result = mycursor.fetchone()

        if result:
            os.system('python main.py')
            messageBox=QMessageBox()
            messageBox.setText("Connexion réussie")
            messageBox.setStandardButtons(QMessageBox.Ok)
            
    
            messageBox.exec()
            #
            # QMessageBox.information(self, "Connexion réussie", "Vous êtes connecté en tant que médecin")
            
            
        else:
            messageBox=QMessageBox()
            messageBox.setText("Erreur de connexion  ,Email ou mot de passe incorrect")
            messageBox.setStandardButtons(QMessageBox.Ok)
            messageBox.exec()

            

    def reset_password(self):
        email = self.nomuti.text()

        mydb = pymysql.connect(
            host="localhost",
            user="root",
            password="",
            database="texthear"
        )

        mycursor = mydb.cursor()

        query = "SELECT * FROM medecin WHERE email = %s"
        values = (email,)
        mycursor.execute(query, values)

        result = mycursor.fetchone()

        if result:
            # Envoyer un email pour réinitialiser le mot de passe
            messageBox=QMessageBox()
            messageBox.setText("Mot de passe oublié , Un email de réinitialisation a été envoyé à votre adresse")
            messageBox.setStandardButtons(QMessageBox.Ok)
            messageBox.exec()
            
        else:
            messageBox=QMessageBox()
            messageBox.setText("Erreur ?Aucun compte trouvé avec cet email")
            messageBox.setStandardButtons(QMessageBox.Ok)
            messageBox.exec()
            


import TRE
import prece










if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    sec= Ui_Form()
    sec.setupUi(Form)

    Form.show()
    sys.exit(app.exec_())