# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medecin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPropertyAnimation



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.fond = QtWidgets.QLabel(self.centralwidget)
        self.fond.setGeometry(QtCore.QRect(0, 0, 1401, 821))
        self.fond.setStyleSheet("background-image: url(background.jpg);")
        self.fond.setText("")
        self.fond.setObjectName("fond")
        self.button_fiche = QtWidgets.QPushButton(self.centralwidget)
        self.button_fiche.setGeometry(QtCore.QRect(300, 280, 251, 341))
        self.button_fiche.setStyleSheet("QPushButton{\n"
"background-color:rgb(0, 178, 238);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(238,213,210);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")
        self.button_fiche.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fiche3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_fiche.setIcon(icon)
        self.button_fiche.setIconSize(QtCore.QSize(100, 100))
        self.button_fiche.setObjectName("button_fiche")
        self.button_cam = QtWidgets.QPushButton(self.centralwidget)
        self.button_cam.setGeometry(QtCore.QRect(560, 280, 241, 341))
        self.button_cam.setStyleSheet("QPushButton{\n"
"background-color:rgb(0, 178, 238);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(238,213,210);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")
        self.button_cam.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("cam4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_cam.setIcon(icon1)
        self.button_cam.setIconSize(QtCore.QSize(100, 100))
        self.button_cam.setObjectName("button_cam")
        self.button_patient = QtWidgets.QPushButton(self.centralwidget)
        self.button_patient.setGeometry(QtCore.QRect(810, 280, 251, 341))
        self.button_patient.setStyleSheet("QPushButton{\n"
"background-color:rgb(0, 178, 238);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(238,213,210);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")
        self.button_patient.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("patient3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_patient.setIcon(icon2)
        self.button_patient.setIconSize(QtCore.QSize(100, 100))
        self.button_patient.setObjectName("button_patient")
        self.frame_sup = QtWidgets.QFrame(self.centralwidget)
        self.frame_sup.setGeometry(QtCore.QRect(0, 0, 1401, 51))
        self.frame_sup.setStyleSheet("background-color:transparent;")
        self.frame_sup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sup.setObjectName("frame_sup")
        self.butt_prof = QtWidgets.QPushButton(self.frame_sup)
        self.butt_prof.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.butt_prof.setStyleSheet("background-color: white;")
        self.butt_prof.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("prof5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butt_prof.setIcon(icon3)
        self.butt_prof.setIconSize(QtCore.QSize(30, 30))
        self.butt_prof.setObjectName("butt_prof")
        self.frame_later = QtWidgets.QFrame(self.centralwidget)
        self.frame_later.setGeometry(QtCore.QRect(0, 0, 161, 200))
        self.frame_later.setStyleSheet("background-color: rgb(0, 178, 238);")
        self.frame_later.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_later.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_later.setObjectName("frame_later")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_later)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_medecin = QtWidgets.QLabel(self.frame_later)
        self.label_medecin.setMaximumSize(QtCore.QSize(500, 100))
        self.label_medecin.setStyleSheet("image: url(1.png);")
        self.label_medecin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_medecin.setText("")
        self.label_medecin.setTextFormat(QtCore.Qt.AutoText)
        self.label_medecin.setPixmap(QtGui.QPixmap(":/icons/icons/1.png"))
        self.label_medecin.setScaledContents(True)
        self.label_medecin.setObjectName("label_medecin")
        self.verticalLayout.addWidget(self.label_medecin)
        self.butt_monprofil = QtWidgets.QPushButton(self.frame_later)
        self.butt_monprofil.setIcon(icon3)
        self.butt_monprofil.setObjectName("butt_monprofil")
        self.butt_monprofil.setMinimumSize(QtCore.QSize(120, 50))
        self.butt_monprofil.setStyleSheet("QPushButton{\n"
"background-color:rgb(95,158,160);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")
        

        self.verticalLayout.addWidget(self.butt_monprofil)
        self.butt_logout = QtWidgets.QPushButton(self.frame_later)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butt_logout.setIcon(icon4)
        self.butt_logout.setObjectName("butt_logout")
        self.butt_logout.setMaximumSize(QtCore.QSize(16777215, 50))
        self.butt_logout.setMinimumSize(QtCore.QSize(120, 50))
        self.butt_logout.setStyleSheet("QPushButton{\n"
"background-color:rgb(95,158,160);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")


        self.verticalLayout.addWidget(self.butt_logout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def deconnexion(self):
        import os
        os.system('python mainprincipale.py')    


       

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.butt_monprofil.setText(_translate("MainWindow", "Mon Profil"))
        self.butt_logout.setText(_translate("MainWindow", "Déconnexion"))
        self.butt_logout.clicked.connect(self.deconnexion)

    
    



import resources_rc

if __name__ == "__main__":
     import sys
     app = QtWidgets.QApplication(sys.argv)
     MainWindow = QtWidgets.QMainWindow()
     ui = Ui_MainWindow()
     ui.setupUi(MainWindow)
     MainWindow.show()
     sys.exit(app.exec_())
