# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inter20.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 947, 626))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setStyleSheet("background-color: rgb(0, 178, 238);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.profil_2 = QtWidgets.QPushButton(self.frame_2)
        self.profil_2.setMinimumSize(QtCore.QSize(120, 50))
        self.profil_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.profil_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 178, 238);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/3177440.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profil_2.setIcon(icon)
        self.profil_2.setIconSize(QtCore.QSize(30, 30))
        self.profil_2.setDefault(False)
        self.profil_2.setFlat(False)
        self.profil_2.setObjectName("profil_2")
        self.verticalLayout_2.addWidget(self.profil_2)
        self.calendrier = QtWidgets.QPushButton(self.frame_2)
        self.calendrier.setMinimumSize(QtCore.QSize(120, 50))
        self.calendrier.setMaximumSize(QtCore.QSize(16777215, 50))
        self.calendrier.setTabletTracking(True)
        self.calendrier.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 178, 238);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/1243872.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendrier.setIcon(icon1)
        self.calendrier.setIconSize(QtCore.QSize(30, 30))
        self.calendrier.setObjectName("calendrier")
        self.verticalLayout_2.addWidget(self.calendrier)
        self.patient = QtWidgets.QPushButton(self.frame_2)
        self.patient.setMinimumSize(QtCore.QSize(120, 50))
        self.patient.setMaximumSize(QtCore.QSize(16777215, 50))
        self.patient.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 178, 238);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  10pt \"MS Shell Dlg 2\";\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/9442121.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patient.setIcon(icon2)
        self.patient.setIconSize(QtCore.QSize(35, 35))
        self.patient.setObjectName("patient")
        self.verticalLayout_2.addWidget(self.patient)
        self.exit = QtWidgets.QPushButton(self.frame_2)
        self.exit.setMinimumSize(QtCore.QSize(120, 50))
        self.exit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.exit.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 178, 238);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font:  12pt \"MS Shell Dlg 2\";\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/10027554.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon3)
        self.exit.setIconSize(QtCore.QSize(30, 30))
        self.exit.setObjectName("exit")
        self.verticalLayout_2.addWidget(self.exit)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.barre = QtWidgets.QFrame(self.frame)
        self.barre.setBaseSize(QtCore.QSize(1000, 1))
        self.barre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.barre.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barre.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barre.setObjectName("barre")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.barre)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.barre)
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit = QtWidgets.QLineEdit(self.barre)
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(0, 178, 238);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit, 0, QtCore.Qt.AlignTop)
        self.search = QtWidgets.QPushButton(self.barre)
        self.search.setBaseSize(QtCore.QSize(11, 11))
        self.search.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.search.setAutoFillBackground(False)
        self.search.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/875623.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon5)
        self.search.setIconSize(QtCore.QSize(25, 25))
        self.search.setAutoRepeat(True)
        self.search.setAutoExclusive(True)
        self.search.setAutoDefault(True)
        self.search.setDefault(True)
        self.search.setFlat(True)
        self.search.setObjectName("search")
        self.horizontalLayout_3.addWidget(self.search, 0, QtCore.Qt.AlignTop)
        self.profil = QtWidgets.QPushButton(self.barre)
        self.profil.setAutoFillBackground(False)
        self.profil.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profil.setIcon(icon6)
        self.profil.setIconSize(QtCore.QSize(25, 25))
        self.profil.setAutoRepeat(True)
        self.profil.setAutoExclusive(True)
        self.profil.setAutoDefault(True)
        self.profil.setFlat(False)
        self.profil.setObjectName("profil")
        self.horizontalLayout_3.addWidget(self.profil, 0, QtCore.Qt.AlignTop)
        
        self.cross = QtWidgets.QPushButton(self.barre)
        self.cross.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cross.setIcon(icon8)
        self.cross.setIconSize(QtCore.QSize(25, 25))
        self.cross.setObjectName("cross")
        self.horizontalLayout_3.addWidget(self.cross, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.barre, 0, QtCore.Qt.AlignTop)
        self.main = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMaximumSize(QtCore.QSize(900, 700))
        self.main.setMouseTracking(True)
        self.main.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.main.setStyleSheet("")
        self.main.setObjectName("main")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.main)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setStyleSheet("image: url(:/newPrefix/14275.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(300, 300))
        self.label_4.setMaximumSize(QtCore.QSize(500, 500))
        self.label_4.setStyleSheet("image: url(:/newPrefix/14527.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.main)
        self.frame_3.setStyleSheet("border-image: url(:/newPrefix/b525e5f2099a28fb54938d6414d704d8.jpg);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.main)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.copiright = QtWidgets.QPushButton(self.frame_6)
        self.copiright.setStyleSheet("color: rgb(0, 178, 238);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/6996499.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copiright.setIcon(icon9)
        self.copiright.setFlat(True)
        self.copiright.setObjectName("copiright")
        self.horizontalLayout_4.addWidget(self.copiright, 0, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setMinimumSize(QtCore.QSize(30, 30))
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/10018177.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.num = QtWidgets.QLabel(self.frame_6)
        self.num.setObjectName("num")
        self.horizontalLayout_4.addWidget(self.num, 0, QtCore.Qt.AlignLeft)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setMinimumSize(QtCore.QSize(25, 25))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/2121954.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.secretaire_mail = QtWidgets.QLabel(self.frame_6)
        self.secretaire_mail.setObjectName("secretaire_mail")
        self.horizontalLayout_4.addWidget(self.secretaire_mail)
        self.verticalLayout.addWidget(self.frame_6, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.profil_2.setText(_translate("MainWindow", "mon profil"))
        self.calendrier.setText(_translate("MainWindow", "Calendrier"))
        self.patient.setText(_translate("MainWindow", "Patient"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.copiright.setText(_translate("MainWindow", "2023 -All Rights Reserved"))
        self.num.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#00b2ee;\">+216 72 556 555</span></p></body></html>"))
        self.secretaire_mail.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#00b2ee;\">secretaire@gmail.com</span></p></body></html>"))
import icon_rc
