# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2031, 1054)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, -20, 891, 171))
        self.label_3.setStyleSheet("font: 72pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(600, 80, 611, 241))
        self.label_2.setStyleSheet("font: 75 72pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 300, 431, 101))
        self.label_6.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(204, 221, 255);")
        self.label_6.setObjectName("label_6")
        self.medecin = QtWidgets.QPushButton(Form)
        self.medecin.setGeometry(QtCore.QRect(50, 430, 231, 221))
        self.medecin.setStyleSheet("")
        self.medecin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images (2).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.medecin.setIcon(icon)
        self.medecin.setIconSize(QtCore.QSize(200, 200))
        self.medecin.setObjectName("medecin")
        self.secretaire = QtWidgets.QPushButton(Form)
        self.secretaire.setGeometry(QtCore.QRect(660, 420, 231, 231))
        self.secretaire.setStyleSheet("")
        self.secretaire.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("En pratique-01.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.secretaire.setIcon(icon1)
        self.secretaire.setIconSize(QtCore.QSize(200, 200))
        self.secretaire.setObjectName("secretaire")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(360, 510, 211, 71))
        self.label.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";\n"
"color: rgb(204, 221, 255);")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(330, 760, 1161, 91))
        self.label_5.setStyleSheet("color: rgb(204, 221, 255);\n"
"text-decoration: underline;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(110, 860, 781, 51))
        self.label_7.setStyleSheet("color: rgb(204, 221, 255);\n"
"text-decoration: underline;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(820, -60, 1231, 1111))
        self.label_4.setStyleSheet("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/pngtree-international-day-of-the-deaf-for-deaf-persons-with-disabilities-png-image_8634105 (1).png"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Bienvenue dans"))
        self.label_2.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:72pt; vertical-align:super;\">TextHear</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "TextHear"))
        self.label_6.setText(_translate("Form", "Êtes-vous"))
        self.label.setText(_translate("Form", "Ou"))
        self.label_5.setText(_translate("Form", "Je Suis  à Moitié Sourd  "))
        self.label_7.setText(_translate("Form", "Mais La Moitié Que Je N\'entends Pas Ne Me Manque Pas !"))
import a_rc
import b_rc
import c_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    sec= Ui_Form()
    sec.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())