# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile_sec.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QMessageBox
import mysql.connector



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("border-image: url(:/newPrefix/nurse.jpg);")
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setMaximumSize(QtCore.QSize(120, 60))
        self.label.setStyleSheet("font: 75 12pt \"System\";\n"
"color: rgb(117, 188, 234);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(60, 40))
        self.label_2.setMaximumSize(QtCore.QSize(60, 60))
        self.label_2.setStyleSheet("font: 75 12pt \"System\";\n"
"color: rgb(117, 188, 234);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setMinimumSize(QtCore.QSize(60, 60))
        self.label_3.setMaximumSize(QtCore.QSize(80, 50))
        self.label_3.setStyleSheet("font: 75 12pt \"System\";\n"
"color: rgb(117, 188, 234);")
        self.label_3.setMidLineWidth(60)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setMinimumSize(QtCore.QSize(60, 60))
        self.label_5.setMaximumSize(QtCore.QSize(80, 60))
        self.label_5.setStyleSheet("font: 75 12pt \"System\";\n"
"color: rgb(117, 188, 234);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setMinimumSize(QtCore.QSize(60, 60))
        self.label_6.setMaximumSize(QtCore.QSize(80, 60))
        self.label_6.setStyleSheet("font: 75 12pt \"System\";\n"
"color: rgb(117, 188, 234);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setStyleSheet("background-color: rgb(117, 188, 234);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setStyleSheet("background-color: rgb(117, 188, 234);")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 1, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_2.setStyleSheet("background-color: rgb(117, 188, 234);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 1, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_3.setStyleSheet("background-color: rgb(117, 188, 234);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout.addWidget(self.textEdit_3, 2, 1, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_4.setStyleSheet("background-color: rgb(117, 188, 234);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout.addWidget(self.textEdit_4, 3, 1, 1, 1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_6.setStyleSheet("background-color: rgb(117, 188, 234);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.gridLayout.addWidget(self.textEdit_6, 7, 1, 1, 1)
        self.textEdit_5 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_5.setStyleSheet("background-color: rgb(117, 188, 234);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout.addWidget(self.textEdit_5, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setMinimumSize(QtCore.QSize(60, 60))
        self.label_4.setMaximumSize(QtCore.QSize(80, 60))
        self.label_4.setStyleSheet("font: 75 12pt \"System\";\n"
"color: rgb(117, 188, 234);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # connexion à la base de données
        self.db = mysql.connector.connect(
            host='localhost',
            user='root',
            password='',
            database='texthear'
       )
    
    def afficher_info_secretaires(self):
        cursor = self.db.cursor()
        id = self.textEdit.toPlainText()  # Récupérer l'ID du secrétaire depuis l'interface
        query = f"SELECT nom, prénom, rotation, numero_telephone, adresse FROM secretaires WHERE id = {id}"  # Créer la requête SQL pour récupérer les informations du secrétaire
        cursor.execute(query)  # Exécuter la requête SQL
        result = cursor.fetchone()  # Récupérer le résultat de la requête

        if result: # si le résultat de la requête n'est pas vide
            # afficher les informations du secrétaire sur les labels
            
            self.textEdit_2.setText(f"Nom: {result[0]}")
            self.textEdit_3.setText(f"Prénom: {result[1]}")
            self.textEdit_5.setText(f"Rotation: {result[2]}")
            self.textEdit_4.setText(f"Numéro de téléphone: {result[3]}")
            self.textEdit_6.setText(f"Adresse: {result[4]}")
        else: # si le résultat de la requête est vide
            messageBox = QMessageBox()
            messageBox.setText("'Erreur Le secrétaire n\'a pas été trouvé dans la base de données")
            messageBox.setStandardButtons(QMessageBox.Ok)
            messageBox.exec() 




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID sécrétaire:"))
        self.label_2.setText(_translate("MainWindow", "Nom:"))
        self.label_3.setText(_translate("MainWindow", "Prénom:"))
        self.label_5.setText(_translate("MainWindow", "Rotation:"))
        self.label_6.setText(_translate("MainWindow", "Adresse:"))
        self.pushButton.setText(_translate("MainWindow", "INFORMATIONS"))
        self.label_4.setText(_translate("MainWindow", "NUM_tél:"))
        self.pushButton.clicked.connect(self.afficher_info_secretaires)

import icon_rc

